### ISSUE TITLE
一个小改动或许会使这个更加稳定

### ISSUE THREAD

**Issue by AbaoFromCUG** [lowbees/FramlessWindowHelper#1]
## 我clone了你这个项目，运行时出现
![question](https://user-images.githubusercontent.com/24972096/30245775-ed8bed76-9616-11e7-87f7-32eca3b26e21.png)

我描述为，启动显示窗口大概0.5s后出现这种情况，高度缩小为minimumHeight
有些时候，还会出现窗口无响应的状态

## 我的改动
在main.cpp中
```cpp
QQmlApplicationEngine engine;
    engine.load(QUrl(QStringLiteral("qrc:/main.qml")));

    if (engine.rootObjects().isEmpty())
        return -1;
    FramelessWindowHelper helper(&engine);

    // 主窗口必须以这种方式
    helper.addWindow("MainWindow");
    return app.exec();
```
改为
```cpp
QQmlApplicationEngine engine;
 FramelessWindowHelper helper(&engine);

    // 主窗口必须以这种方式
    helper.addWindow("MainWindow");
    engine.load(QUrl(QStringLiteral("qrc:/main.qml")));

    if (engine.rootObjects().isEmpty())
        return -1;
   
    return app.exec();
```
就不会出现那种问题

**Comment by AbaoFromCUG** [comment]
## 另外，由于代码中第二个窗口TestPage也是在加载完后，才addWindow中，所以也会缩小为最小的大小，这里没有设置最小的大小，于是就变成了一条线
```qml
Component.onCompleted: FramelessWindowHelper.addWindow(objectName)
```
额，这个我就不太会解决了
wait you reply

**Comment by lowbees** [comment]
1.请说明你的环境
2.窗口无响应状态可能是因为我把标题栏的cursorShape设置为了Busy状态，你看是不是因为这个原因
3.只有load qml之后才能addWindow，addWindow放在load之前应该就没缩放效果了
4.我的环境是win7+qt5.8+mingw，并没有出现你所说的问题

**Comment by lowbees** [comment]
@AbaoFromCUG 
1.请说明你的环境
2.窗口无响应状态可能是因为我把标题栏的cursorShape设置为了Busy状态，你看是不是因为这个原因
3.只有load qml之后才能addWindow，addWindow放在load之前应该就没缩放效果了
4.我的环境是win7+qt5.8+mingw，并没有出现你所说的问题

**Comment by AbaoFromCUG** [comment]
@lowbees 
-  我的环境
   >Qt 5.9.1 (x86_64-little_endian-lp64 shared (dynamic) release build; by GCC 7.1.0) on "xcb" 
OS: Parrot GNU/Linux 3.8 JollyRoger [linux version 4.12.0-parrot6-amd64]
Qt Creator 4.3.1
Based on Qt 5.9.1 (GCC 7.2.0, 64 bit)

- 无响应是发生在标题栏错位后发生的
- 对的，在main函数里先addWindow的确会使得窗口没有缩放效果（原来我一直没注意到），但是当启动第二个窗口后main窗口又可以缩放了

- 我没有在window上试过，感觉应该是Linux的图像界面的渲染问题导致的

**Comment by lowbees** [comment]
@AbaoFromCUG 

1. 没用过linux，抱歉
2. 此问题是因为load在addWindow之后引起的，而第二个窗口启动后主窗口又可以缩放了是因为addWindow函数会检测主窗口有没有加入可缩放，没有加入则会自动加入
3. 我采用了一种新的方式，希望可以解决你的启动之后窗口会缩成最小高度和最小宽度的问题
